name: Releases

on:
  push:
    tags:
      - "*"

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@master

      - name: Install Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "21.5.0"

      - name: Install pnpm
        run: npm install -g pnpm

      - name: Install npm dependencies
        run: pnpm install

      - name: Run build task
        run: pnpm run build

      - name: Create ZIP
        uses: thedoctor0/zip-release@0.7.5
        with:
          type: "zip"
          filename: "flomotab.zip"
          path: "./extension"

      - name: Release ZIP
        uses: ncipollo/release-action@v1.12.0
        with:
          artifacts: "flomotab.zip"
          body: "version: ${{ github.ref_name }}"
          bodyFile: "flomotab.zip"
          token: ${{ secrets.TOKEN }}
